trigger:
  branches:
    exclude:
      - release
      - dev

pool:
  vmImage: 'ubuntu-20.04'

container: kaiiz3n/books-api-base:latest

steps:
- script: |
    cd tests
    python -m pytest -v $(Build.SourcesDirectory)/tests/
  env:
    PYTHONPATH: $(Build.SourcesDirectory)/app
  displayName: 'Run Tests'
