trigger:
  branches:
    exclude:
      - release
      - dev

pool:
  vmImage: 'ubuntu-20.04'

container: kaiiz3n/books-api-base:latest

steps:
- script: |
    docker run fast-api:$(Build.BuildId) python -m pytest
  env:
    PYTHONPATH: $(Build.SourcesDirectory)
  displayName: 'Run Tests'
