trigger:
  branches:
    exclude:
      - release
      - dev

pool:
  vmImage: 'ubuntu-20.04'

container: kaiiz3n/books-api-base:latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Python 3.7'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    python -m pytest
  displayName: 'pytest'